#!/usr/bin/env python
from character_profile import Character

class Richard:
    def __init__(self,skill,level,build):
        #Initiate Richard with input of skills
        self.skill = skill
        self.level = self.talent_tree(level,build)
       
    def talent_tree(level,build):
        defense = [self.all_defense(0.5),self.all_attack(0.5),self.all_attack(0.5),self.all_attack(0.5),...
                   self.increase_counterattack(0.5),self.increase_counterattack(0.5),self.increase_counterattack(0.5),...
                   self.all_attack(0.5),self.reduce_skill_damage_taken(3),self.reduce_skill_damage_taken(3),self.reduce_skill_damage_taken(3),...
                   self.reduce_damage_taken(0.5),self.reduce_damage_taken(0.5),self.reduce_damage_taken(0.5),...
                   self.all_attack(0.5),self.all_attack(0.5),self.all_health(0.5),self.all_health(0.5),self.all_health(0.5),...
                   self.heal_slightly_wounded(100),self.heal_slightly_wounded(100),self.heal_slightly_wounded(100),..
                   self.all_defense(0.5),self.all_defense(0.5),self.all_defense(0.5),...
                   self.defense_star(0.5),self.defense_star(0.5),self.defense_star(0.5),self.all_health(0.5),...
                   self.reduce_damage_taken_and_dealt(1,0.5),self.reduce_damage_taken_and_dealt(1,0.5),self.reduce_damage_taken_and_dealt(1,0.5),...
                   self.add_rage(2),self.add_rage(2),self.add_rage(2),self.march_speed(3),self.march_speed(3),...
                   self.all_defense(0.5),self.all_defense(0.5),self.all_defense(0.5),...
                   self.chance_reduce_damage_taken(5),self.chance_reduce_damage_taken(5),self.chance_reduce_damage_taken(5),...
                   self.thirty_percent_rage_accum(30,25),self.thirty_percent_rage_accum(30,25),self.thirty_percent_rage_accum(30,25),...
                   self.percent_rage_accum(30,25),self.thirty_percent_rage_accum(30,25)]
        
        infantry = [self.inf_defense(1),self.inf_defense(1),self.inf_defense(1),...
                    self.percent_all_defense(50,2),self.percent_all_defense(50,2),self.percent_all_defense(50,2),...
                    self.inf_health(1),self.inf_health(1),self.inf_health(2),self.inf_health(2),self.inf_health(2),...
                    self.normal_attack_damage(0.5),self.normal_attack_damage(0.5),self.normal_attack_damage(0.5),...
                    self.inf_defense(1),self.inf_defense(1),self.inf_defense(1),self.inf_health(1),self.inf_health(1),...
                    self.chance_inf_reduce_damage_taken(10,5,2),self.chance_inf_reduce_damage_taken(10,5,2),...
                    self.chance_inf_reduce_damage_taken(10,5,2),self.chance_inf_reduce_damage_taken(10,5,2),...
                    self.rage_accum(3),self.rage_accum(3),self.rage_accum(3),...
                    self.inf_attack(1),self.inf_attack(1),self.inf_attack_cav(1),self.inf_attack_cav(1),self.inf_attack_cav(1),...
                    self.march_inf_speed(3),self.march_inf_speed(3),self.march_inf_speed(3),self.march_inf_speed(3),...
                    self.march_inf_speed(2),self.march_inf_speed(2),self.march_inf_speed(2),self.inf_health(1),...
                    self.inf_attack(1),self.inf_attack(1),self.chance_reduce_march_speed(10,5,2),self.chance_reduce_march_speed(10,5,2),...
                    self.chance_reduce_march_speed(10,5,2),self.chance_reduce_march_speed(10,5,2),self.inf_all_buffs(0.5),...
                    self.inf_all_buffs(0.5),self.inf_all_buffs(0.5),self.inf_all_buffs(0.5),self.inf_all_buffs(0.5)]
                    
        garrison = [self.all_defense(0.5),self.all_attack(0.5),self.all_attack(0.5),self.garrison_damage_dealt(2),...
                    self.garrison_damage_dealt(2),self.garrison_damage_dealt(2),self.all_health(0.5),...
                    self.garrison_skill_damage_reduction(5),self.garrison_skill_damage_reduction(5),self.garrison_skill_damage_reduction(5),...
                    self.garrison_damage_taken_reduced(2),self.garrison_damage_taken_reduced(2),self.garrison_damage_taken_reduced(2),...
                    self.all_defense(0.5),self.garrison_rage_accum(2),self.garrison_rage_accum(2),self.garrison_rage_accum(2),...
                    self.all_attack(0.5),self.all_attack(0.5),self.all_health(0.5),self.all_health(0.5),...
                    self.all_defense(0.5),self.all_defense(0.5),self.all_health(0.5),self.all_health(0.5),...
                    self.watchtower_defense(5),self.watchtower_defense(5),self.watchtower_defense(5),...
                    self.watchtower_attack(5),self.watchtower_attack(5),self.watchtower_attack(5),...
                    self.all_attack(0.5),self.all_attack(0.5),self.all_defense(0.5),self.all_defense(0.5),...
                    self.garrison_surround_damage_reduction(3),self.garrison_surround_damage_reduction(3),self.garrison_surround_damage_reduction(3),...
                    self.garrison_all_stats(1),self.garrison_all_stats(1),self.garrison_all_stats(1),...
                    self.chance_shield(10,100),self.chance_shield(10,100),self.chance_shield(10,100),self.chance_shield(10,100),...
                    self.chance_shield(10,100),self.march_speed(3),self.march_speed(3),self.march_speed(3)]
            
    def attack(self):
        self.skills()
        self.talents()
        return
        
class March:
    def __init__(self,primary,secondary,troop):
        self.primary = primary
        self.secondary = secondary
        self.troop = troop
            
    
    

primary = 'Richard'
secondary = 'Charles'
build_Richard = [1,0,0,0]
build_Charles = [1,0,0,0]
tech = [70,70,40,70,70,40,70,70,40]
alliance_tech = [15,15,0,15,15,0,15,15,0]
titles = [0,0,0,0,0,0,0,0,0]
holy_sites = [6,6,5,6,6,5,6,6,5]
building = [2,2,6,2,2,6,2,2,6]
vip = 15
troop_amount = 200000



kevin = Character('Ottoman')
print(kevin.aa,kevin.sh,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
#kevin.civilization('Germany')
#print(kevin.aa,kevin.sh,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
kevin.city_theme_buffs('No Place Like Home')
print(kevin.aa,kevin.sh,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
kevin.technology_buffs(tech)
print(kevin.aa,kevin.sh,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
kevin.alliance_buffs(alliance_tech)
print(kevin.aa,kevin.sh,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
kevin.alliance_buffs(holy_sites)
print(kevin.aa,kevin.sh,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
kevin.building_buffs(building)
print(kevin.aa,kevin.sh,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
kevin.vip_buffs(vip)
print(kevin.aa,kevin.ad,kevin.ah,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
print(kevin.buffs_ia,kevin.buffs_id,kevin.buffs_ih,kevin.buffs_ca,kevin.buffs_cd,kevin.buffs_ch,kevin.buffs_aa,kevin.buffs_ad,kevin.buffs_ah,kevin.buffs_skill,kevin.buffs_rally,kevin.buffs_counter)
kevin.change_civ('Germany')
print(kevin.aa,kevin.ad,kevin.ah,kevin.buffs_ca,kevin.buffs_id,kevin.buffs_skill,kevin.buffs_rally,kevin.ca)
print(kevin.buffs_ia,kevin.buffs_id,kevin.buffs_ih,kevin.buffs_ca,kevin.buffs_cd,kevin.buffs_ch,kevin.buffs_aa,kevin.buffs_ad,kevin.buffs_ah,kevin.buffs_skill,kevin.buffs_rally,kevin.buffs_counter)
